server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  # 连接码云远程仓库
  cloud:
    config:
      server:
        git:
          # 注意是https的而不是ssh
          # 通过 config-server可以连接到git，访问其中的资源以及配置~
          uri: https://gitee.com/hanqi-kelvin/springcloud-config.git