server:
  port: 9527

spring:
  application:
    name: springcloud-zuul #微服务名称

#eureka 注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: #实例的id
    instance-id: zuul9527.com
    prefer-ip-address: true # 显示ip

info:
  app.name: kelvin.springcloud # 项目名称
  company.name: YYKJ # 公司名称

# zull 路由网关配置
zuul:
  # 路由相关配置
  # 原来访问路由 eg:http://www.yykj.com:9527/springcloud-provider-dept/dept/get/1
  # zull路由配置后访问路由 http://www.yykj.com:9527/myservice/dept/get/1
  routes:
    myservice.serviceId: springcloud-provider-dept # eureka注册中心的服务提供方路由名称
    myservice.path: /myservice/** # 将eureka注册中心的服务提供方路由名称 改为自定义路由名称
  # 不能再使用这个路径访问了，*： 忽略,隐藏全部的微服务名称~
  ignored-services:
    - "*"
    #- springcloud-provider-dept  #不能再使用这个路径访问了
  prefix: /springcloud     #前缀 例如：http://www.yykj.com:9527/springcloud/myservice/dept/get/1
