server:
  port: 7002

#Eureka配置
eureka:
  instance:
    hostname: eureka7002.com #服务端的实例名称
  client:
    register-with-eureka: false #是否向Eureka服务中心注册 本例为Server故不用注册
    fetch-registry: false #false 表示本身为注册中心
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka #集群关联
